# Copyright (c) 2023 Sophie Tyalie
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: manifest

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: km
      url-base: https://github.com/tyalie

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - hal_espressif
          - mcuboot
          - mbedtls
    - name: heatshrink
      remote: km
      revision: develop
      path: modules/lib/heatshrink
